# Generated by Django 4.1.1 on 2022-10-31 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mypanel", "0010_remove_customer_address_customer_phone_and_more"),
        ("kalkulator", "0002_rename_kalkulator_calculation"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculation",
            name="requiredarea",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="calculation", name="electricity", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="calculation", name="envfactor", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="calculation", name="offset", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="calculation", name="panel", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="calculation", name="roofarea", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="calculation", name="sizeestimate", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="calculation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mypanel.customer"
            ),
        ),
    ]
