# Generated by Django 4.1.1 on 2022-11-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kalkulator", "0003_calculation_requiredarea_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculation",
            name="is_doable",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
