# Generated by Django 4.1 on 2022-11-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycart', '0006_alter_order_customer_alter_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='on_process',
            field=models.BooleanField(default=False),
        ),
    ]
