# Generated by Django 4.1 on 2022-10-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypanel', '0007_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_technician',
            field=models.BooleanField(default=False),
        ),
    ]
