# Generated by Django 4.1 on 2022-10-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypanel', '0008_customer_is_technician'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
