# Generated by Django 4.1 on 2022-10-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artikel',
            name='like',
        ),
        migrations.AddField(
            model_name='artikel',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
