# Generated by Django 4.1 on 2022-10-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_mainaddress_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainaddress',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='mainaddress',
            name='kecamatan',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='mainaddress',
            name='kelurahan',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='mainaddress',
            name='kota',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='mainaddress',
            name='postcode',
            field=models.CharField(default='', max_length=200),
        ),
    ]
