# Generated by Django 4.1 on 2022-11-02 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mypanel', '0012_remove_inverter_product_ptr_remove_panel_product_ptr_and_more'),
        ('testimoni', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testitemplate',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mypanel.customer'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('answer_text', models.TextField(max_length=50000)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.TextField(max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypanel.customer')),
            ],
        ),
    ]
